import Foundation
import XCTest
@testable import LiveLingo

@MainActor
final class MultilingualLearningNotesTests: XCTestCase {
    private var englishEvidence: [TranscriptSegment] {
        [TranscriptSegment(startTime: 0, endTime: 2, english: "Ice is cold. Water flows.", chinese: "冰很冷。水会流动。"),
         TranscriptSegment(startTime: 2, endTime: 3, english: "Heat moves.", chinese: "热会传递。")]
    }

    private func batch(_ evidence: [TranscriptSegment]) -> LearningNoteBatch {
        LearningNoteBatch(id: UUID(), evidence: evidence,
            note: LearningNote(topic: "Heat", points: [LearningPoint(kind: "核心结论", text: "热会传递。",
                sources: [.init(index: 1, quote: "热会传递。")])]))
    }

    // Frozen on b614a3c before changing the production paths. These literals
    // must not be regenerated by the implementation being tested.
    func testEnglishLearningInputsAndDigestsMatchFrozenStep6Bytes() throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        let expectedUnits = #"[{"id":"en0s0","index":0,"language":"en","text":"Ice is cold."},{"id":"en0s1","index":0,"language":"en","text":"Water flows."},{"id":"zh0s0","index":0,"language":"zh","text":"冰很冷。"},{"id":"zh0s1","index":0,"language":"zh","text":"水会流动。"},{"id":"en1s0","index":1,"language":"en","text":"Heat moves."},{"id":"zh1s0","index":1,"language":"zh","text":"热会传递。"}]"#
        XCTAssertTrue(try encoder.encode(LearningSourceUnit.make(englishEvidence)) == Data(expectedUnits.utf8))
        let expectedGeneration = #"{"evidence":[{"id":"en0s0","index":0,"language":"en","text":"Ice is cold."},{"id":"en0s1","index":0,"language":"en","text":"Water flows."},{"id":"zh0s0","index":0,"language":"zh","text":"冰很冷。"},{"id":"zh0s1","index":0,"language":"zh","text":"水会流动。"},{"id":"en1s0","index":1,"language":"en","text":"Heat moves."},{"id":"zh1s0","index":1,"language":"zh","text":"热会传递。"}],"pendingPoints":[]}"#
        XCTAssertTrue(Data(try LearningPrompts.input(evidence: englishEvidence, topics: []).utf8)
            == Data(expectedGeneration.utf8))
        let expectedReview = #"{"evidence":[{"index":0,"quotes":[{"id":"e0.en.0","language":"en","text":"Ice is cold. Water flows."},{"id":"e0.zh.0","language":"zh","text":"冰很冷。水会流动。"}]},{"index":1,"quotes":[{"id":"e1.en.0","language":"en","text":"Heat moves."},{"id":"e1.zh.0","language":"zh","text":"热会传递。"}]}],"laterContext":[],"laterEvidence":[],"laterEvidenceOmittedCount":0,"note":{"points":[{"index":0,"kind":"核心结论","sources":[{"index":1,"quote":"热会传递。"}],"text":"热会传递。"}],"topic":"Heat"},"omittedEarlierCandidates":0,"reviewVersion":2}"#
        let prepared = try LearningPrompts.reviewInput(batch(englishEvidence))
        XCTAssertTrue(Data(prepared.json.utf8) == Data(expectedReview.utf8))
        XCTAssertEqual(SessionArchiveCoding.digest(Data(LearningPrompts.generate.utf8)),
            "b7429da5ca0fff3d4817ffaefcc05991186f90026a567d42c7092ec91cfb5d38")
        XCTAssertEqual(SessionArchiveCoding.digest(Data(LearningPrompts.review.utf8)),
            "ab5bce580c7f4ba53cb7ac419e51dbfdcf1517315e0869cc16272ae8fd916fcd")
        XCTAssertEqual(LearningReviewQueue.prefixDigest(json: prepared.json, prompt: LearningPrompts.review),
            "52b48a1e6e90e950d7b93cb2484921d5d5f667e5c47ea57374514ac64978f085")
    }

    func testEnglishSummaryMatchesFrozenStep6Bytes() {
        let expected = """
        [00:00]
        EN: Ice is cold. Water flows.
        ZH: 冰很冷。水会流动。

        [00:02]
        EN: Heat moves.
        ZH: 热会传递。
        """
        XCTAssertTrue(Data(LectureSummaryInput.make(from: englishEvidence).utf8) == Data(expected.utf8))
    }

    func testNonEnglishUnitsAndGenerationUseOnlyChineseGroup() throws {
        let evidence = [
            TranscriptSegment(startTime: 0, endTime: 1, english: "冰很冷。", chinese: "另一段译文。", sourceLanguage: "zh"),
            TranscriptSegment(startTime: 1, endTime: 2, english: "El agua fluye.", chinese: "水会流动。", sourceLanguage: "es"),
            TranscriptSegment(startTime: 2, endTime: 3, english: "水會流㗎。", chinese: "水会流动。", sourceLanguage: "yue")
        ]
        let expected = [
            LearningSourceUnit(id: "zh0s0", index: 0, language: "zh", text: "冰很冷。"),
            LearningSourceUnit(id: "zh1s0", index: 1, language: "zh", text: "水会流动。"),
            LearningSourceUnit(id: "zh2s0", index: 2, language: "zh", text: "水会流动。")
        ]
        XCTAssertTrue(LearningSourceUnit.make(evidence) == expected)
        let input = try LearningPrompts.input(evidence: evidence, topics: [])
        let root = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(input.utf8)) as? [String: Any])
        let units = try XCTUnwrap(root["evidence"] as? [[String: Any]])
        XCTAssertEqual(units.compactMap { $0["language"] as? String }, ["zh", "zh", "zh"])
        XCTAssertTrue(units.compactMap { $0["text"] as? String } == expected.map(\.text))
    }

    func testReviewNonEnglishQuotesUseTargetTextWithoutEnglishWarning() throws {
        let longTranslation = String(repeating: "热量", count: 20) + "。"
        let evidence = [
            TranscriptSegment(startTime: 0, endTime: 1, english: "冰很冷。", chinese: longTranslation, sourceLanguage: "zh"),
            TranscriptSegment(startTime: 1, endTime: 2, english: "Calor.", chinese: longTranslation, sourceLanguage: "es"),
            TranscriptSegment(startTime: 2, endTime: 3, english: "Heat.", chinese: longTranslation)
        ]
        XCTAssertNotNil(LearningPrompts.chineseWarning(chinese: longTranslation, english: "Calor."))
        let prepared = try LearningPrompts.reviewInput(batch(evidence))
        let root = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(prepared.json.utf8)) as? [String: Any])
        let rows = try XCTUnwrap(root["evidence"] as? [[String: Any]])
        XCTAssertEqual(Set(prepared.catalog.keys), ["e0.zh.0", "e1.zh.0", "e2.en.0", "e2.zh.0"])
        XCTAssertTrue(prepared.quote(for: "e0.zh.0")?.text == evidence[0].english)
        XCTAssertTrue(prepared.quote(for: "e1.zh.0")?.text == evidence[1].chinese)
        XCTAssertNil(rows[0]["chineseWarning"])
        XCTAssertNil(rows[1]["chineseWarning"])
        XCTAssertNotNil(rows[2]["chineseWarning"])
    }

    func testReviewLaterNonEnglishEvidenceHasOnlyChineseUnits() throws {
        let source = TranscriptSegment(startTime: 0, endTime: 1, english: "Heat moves.", chinese: "热量传递。")
        let later = [
            TranscriptSegment(startTime: 1, endTime: 2, english: "热量传递。", chinese: "热量传递。", sourceLanguage: "zh"),
            TranscriptSegment(startTime: 2, endTime: 3, english: "El calor se mueve.", chinese: "热量传递。", sourceLanguage: "es")
        ]
        let prepared = try LearningPrompts.reviewInput(batch([source]), laterBatches: [batch(later)])
        let root = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(prepared.json.utf8)) as? [String: Any])
        let rows = try XCTUnwrap(root["laterEvidence"] as? [[String: Any]])
        let units = rows.compactMap { $0["source"] as? [String: Any] }
        XCTAssertEqual(units.compactMap { $0["language"] as? String }, ["zh", "zh"])
        XCTAssertEqual(units.compactMap { $0["id"] as? String }, ["zh0s0", "zh1s0"])
    }

    func testChineseSummaryCountsSourceOnceInBothBudgets() {
        let evidence = [
            TranscriptSegment(startTime: 0, endTime: 1, english: "冰很冷。", chinese: "冰很冷。", sourceLanguage: "zh"),
            TranscriptSegment(startTime: 1, endTime: 2, english: "水会流动。", chinese: "水会流动。", sourceLanguage: "zh")
        ]
        let first = "[00:00]\nZH: 冰很冷。"
        let second = "[00:01]\nZH: 水会流动。"
        let maximum = first.count + second.count
        XCTAssertTrue(LectureSummaryInput.make(from: evidence, maximumCharacters: maximum) == first + "\n\n" + second)
        let incremental = LectureSummaryInput.incremental(from: evidence, coveredIDs: [], previousSummary: "",
            maximumCharacters: evidence.reduce(0) { $0 + $1.english.count + 32 })
        XCTAssertEqual(incremental.segmentIDs, Set(evidence.map(\.id)))
        XCTAssertTrue(incremental.text.hasSuffix(first + "\n\n" + second))
    }

    func testInferredLegacyChineseProducesOnlyOneGroup() throws {
        let raw = #"{"id":"00000000-0000-0000-0000-000000000078","startTime":0,"endTime":1,"english":"冰很冷。","chinese":"冰很冷。"}"#
        let segment = try JSONDecoder().decode(TranscriptSegment.self, from: Data(raw.utf8))
        XCTAssertEqual(segment.sourceLanguage, "zh")
        let units = LearningSourceUnit.make([segment])
        XCTAssertEqual(units.map(\.language), ["zh"])
        XCTAssertTrue(units.map(\.text) == ["冰很冷。"])
        let review = try LearningPrompts.reviewInput(batch([segment]))
        XCTAssertEqual(Set(review.catalog.keys), ["e0.zh.0"])
    }
}
